filebender/django/filebender/bigfiles/urls.py
from django.conf.urls.defaults import patterns
from django.conf import settings

urlpatterns = patterns('',
    (r'^list/$', 'bigfiles.views.listfiles'),
    (r'^download/(?P<bigfileid>\d+)/(?P<secret>\w{%i})/$'
        % settings.FILE_SECRET_LENGTH, 'bigfiles.views.download'),
    (r'^append.json/(?P<bigfileid>\d+)/$', 'bigfiles.views.append'),
    (r'^delete/(?P<bigfileid>\d+)/$', 'bigfiles.views.delete'),
    (r'^upload/$', 'bigfiles.views.upload'),
    (r'^upload.json/$', 'bigfiles.views.upload', {'json': True}),
    (r'^$', 'bigfiles.views.listfiles'),
)

filebender/django/filebender/urls.py
from django.conf.urls.defaults import *
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    (r'^bigfiles/', include('bigfiles.urls')),
    (r'^admin/', include(admin.site.urls)),


    (r'^accounts/login/$', 'django.contrib.auth.views.login'),
    (r'^accounts/logout/$', 'django.contrib.auth.views.logout'),
    (r'^$', include('bigfiles.urls')),
)

if settings.USE_SAML2:
    urlpatterns += patterns('',
        (r'^saml2/', include('djangosaml2.urls')),
        (r'^idp/', include('saml2idp.urls')),
        (r'^sp/', include('saml2sp.urls')),
    )

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
        (r'^storage/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STORAGE_ROOT}),

    )

filebender/django/filebender/bigfiles/models.py
from string import hexdigits
from random import choice
import datetime

from django.db import models
from django.contrib.auth.models import User
from django.conf import settings


# TODO: collision possible, this could be concatenated with bigfileid
def secret_generator(size=settings.FILE_SECRET_LENGTH):
    return "".join([choice(hexdigits) for i in range(size)])


def one_week_later(when=datetime.datetime.now()):
    return  when + datetime.timedelta(weeks=1)


class BigFile(models.Model):
    name = models.CharField(max_length=100)
    size = models.IntegerField()
    md5 = models.CharField(max_length=32)
    expire_date = models.DateTimeField(default=one_week_later)
    upload_date = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, related_name='bigfiles')
    message = models.TextField(blank=True)
    secret = models.CharField(max_length=settings.FILE_SECRET_LENGTH,
                              default=secret_generator)
    
    def __unicode__(self):
        return self.name

    def save(self, *args, **kwargs):
        super(BigFile, self).save(*args, **kwargs)


class Downloader(models.Model):
    bigfile = models.ForeignKey(BigFile, related_name="downloaders")
    email = models.EmailField()

    def __unicode__(self):
        return self.email

filebender/django/filebender/bigfiles/forms.py
from django import forms
from bigfiles.models import one_week_later

class UploadForm(forms.Form):
    file = forms.FileField('File')
    message = forms.CharField(widget=forms.Textarea(),label='Message',
                              required=False)
    receiver = forms.EmailField(label='Receiver', required=False)
    expire_date = forms.DateTimeField(label='Expire date',
                              initial=one_week_later, required=False)

filebender/django/filebender/bigfiles/views.py
import os.path
import hashlib
import shutil

from django.contrib.auth.decorators import login_required
from django.template import RequestContext
from django.shortcuts import render_to_response, get_object_or_404
from django.template.loader import render_to_string
from django.http import HttpResponseRedirect, Http404, HttpResponse
from django.conf import settings
from django.core.mail import send_mail
from django.contrib.sites.models import Site
from django.utils import simplejson

from models import BigFile, Downloader, one_week_later
from forms import UploadForm


@login_required
def listfiles(request):
    bigfiles = request.user.bigfiles.all()
    return render_to_response('bigfiles/list.html', {'bigfiles': bigfiles},
                              context_instance=RequestContext(request))


def mailit(to, from_, message, url):
    """
    compose and send an email
    """
    context = {'from': from_, 'url': url}
    body = render_to_string('email/download.html', context)
    send_mail('FileBender has a file for you!',
              body,
              'gijs@pythonic.nl',
    to, fail_silently=True)
    

def handle_uploaded_file(filename, secret, filedata):
    """
    Stores file into STORAGE. Returns MD5 of file
    """
    file_folder = os.path.join(settings.STORAGE_ROOT, secret)
    
    if not os.access(file_folder, os.F_OK):
        os.mkdir(file_folder)
        
    m = hashlib.md5()
    file_path = os.path.join(file_folder, filename)
    with open(file_path, 'wb+') as destination:
        for chunk in filedata.chunks():
            m.update(chunk)
            destination.write(chunk)
    return m.hexdigest()


@login_required
def upload(request, json=False):
    if request.method == 'GET':
        form = UploadForm()
                
    if request.method == 'POST':
        form = UploadForm(request.POST, request.FILES)
        if form.is_valid():
            data = request.FILES['file']
            name = form.cleaned_data['file'].name
            size = form.cleaned_data['file'].size
            expire_date = form.cleaned_data['expire_date'] or one_week_later()
            message = form.cleaned_data['message']
            receiver = form.cleaned_data['receiver']

            bigfile = BigFile(name=name, owner=request.user,
                        expire_date=expire_date, message=message, size=size)

            md5 = handle_uploaded_file(name, bigfile.secret, data)
            bigfile.md5 = md5
            bigfile.save()

            if receiver:
                downloader = Downloader(email=receiver, bigfile=bigfile)
                downloader.save()
                url = 'http://%s/bigfiles/download/%s/%s' % \
                    (Site.objects.get_current().domain, bigfile.id, bigfile.secret)
                from_ = request.user.email
                mailit([receiver], from_, message, url)
                
            if json:
                response = {'status': 'ok', 'fileid': bigfile.id}
                return HttpResponse(simplejson.dumps(response))
            else:
                return HttpResponseRedirect('/bigfiles/list/')

    if json:
        response = {'status': 'error', 'message': 'form not valid'}
        return HttpResponse(simplejson.dumps(response))
    else:   
        return render_to_response('bigfiles/upload.html', {'form': form,},
                              context_instance=RequestContext(request))


def append(request, bigfileid):
    if request.method != 'POST':
        response = {'status': 'error', 'message': 'expected a post'}
        return HttpResponse(simplejson.dumps(response))

    form = UploadForm(request.POST, request.FILES)
    if not form.is_valid():
        response = {'status': 'error', 'message': 'no file'}
        return HttpResponse(simplejson.dumps(response))        
        
    bigfile = get_object_or_404(BigFile, pk=bigfileid)

    if request.user != bigfile.owner:
        raise Http404
     
    data = request.FILES['file']
    size = form.cleaned_data['file'].size
    filelocation = os.path.join(settings.STORAGE_ROOT, bigfile.secret, bigfile.name)
    
    if not os.access(filelocation, os.F_OK):
        raise Http404
        
    md5 = hashlib.md5()

    # recalculate md5 for existing blob
    with open(filelocation,'rb') as f: 
        for chunk in iter(lambda: f.read(8192), ''): 
            md5.update(chunk)
         
    with open(filelocation, 'ab') as f:
        for chunk in data.chunks():
            md5.update(chunk)
            f.write(chunk)

    bigfile.md5 = md5.hexdigest()
    bigfile.size = bigfile.size + size
    bigfile.save()
    
    response = {'status': 'ok', 'md5': bigfile.md5}
    return HttpResponse(simplejson.dumps(response))  
    

def download(request, bigfileid, secret):
    bigfile = get_object_or_404(BigFile, pk=bigfileid)
    if secret != bigfile.secret:
        raise Http404
    return render_to_response('bigfiles/download.html', {'bigfile': bigfile},
                              context_instance=RequestContext(request))


@login_required
def delete(request, bigfileid):
    bigfile = get_object_or_404(BigFile, pk=bigfileid)

    if request.user != bigfile.owner:
        raise Http404
    
    file_folder = os.path.join(settings.STORAGE_ROOT, bigfile.secret)
    bigfile.delete()

    try:
        shutil.rmtree(file_folder)
    except OSError:
        # file probably already gone
        pass
     
    return HttpResponseRedirect('/bigfiles/list/')

filebender/templates/bigfiles/download.html
{% extends "base.html" %}

{% block content %}

<script src="{{ MEDIA_URL }}js/sjcl.js" type="text/javascript"></script>
<script src="{{ MEDIA_URL }}js/downloader.js" type="text/javascript"></script>
<script src="{{ MEDIA_URL }}js/FileSaver.js" type="text/javascript"></script>
<script src="{{ MEDIA_URL }}js/BlobBuilder.js" type="text/javascript"></script>


    
<h3>File Info</h3>
<table>
<tr><td>File name</td><td>{{ bigfile.name }}</td></tr>
<tr><td>Upload date</td><td>{{ bigfile.upload_date }}</td></tr>
<tr><td>Expire date</td><td>{{ bigfile.expire_date }}</td></tr>
<tr><td>Size</td><td>{{ bigfile.size|filesizeformat }}</td></tr>
<tr><td>Message</td><td>{{ bigfile.message }}</td></tr>
<tr><td>MD5</td><td>{{ bigfile.md5 }}</td></tr>
<tr><td>URL</td><td><a href="{{ STORAGE_URL }}{{ bigfile.secret }}/{{ bigfile.name }}">{{ STORAGE_URL }}{{ bigfile.secret }}/{{ bigfile.name }}</a></td></td></tr>
<tr><td>decrypt</td><td><a hreft="void(0)" onclick="downloader.start('{{ STORAGE_URL }}{{ bigfile.secret }}/{{ bigfile.name }}/', '{{ bigfile.name }}');">click here to decrypt this file</a></td>
</table>



<h3>Downloaders</h3>
{% if bigfile.downloaders %}
    <table>
    <tr>
    {% for downloader in bigfile.downloaders.all %}
        <td>{{ downloader.email }}</td>
    {% endfor %}
    </tr>
    </table>
{% else %}
    No downloaders
{% endif %}

{% endblock %}

filebender/templates/bigfiles/list.html
{% extends "base.html" %}


{% block pagetitle %}
<h2>File List</h2>
{% endblock %}

{% block content %}

{% if bigfiles %}



    <table border="1">
    <tr>
    <td><b>Direct Link</b></td>
    <td><b>Download page</b></td>
    <td><b>Upload date</b></td>
    <td><b>Expire Date</b></td>
    <td><b>MD5</b></td>
    <td><b>Delete</b></td>
    </tr>
 	{% for bigfile in bigfiles %}
       <tr>
	   <td><a href="{{ STORAGE_URL }}/{{ bigfile.secret }}/{{ bigfile.name }}">{{ bigfile.name }}</a></td>
	   <td><a href="/bigfiles/download/{{ bigfile.id }}/{{ bigfile.secret }}/">download</a></td>
       <td>{{ bigfile.upload_date }}</td>
       <td>{{ bigfile.expire_date }}</td>
       <td>{{ bigfile.md5 }}</td>
	   <td><a href="/bigfiles/delete/{{ bigfile.id }}/">delete</a></td>
	   </tr>
	{% endfor %}
	</table>
{% else %}
	No Files
{% endif %}


{% endblock %}


<tr><td>File name</td><td>{{ bigfile.name }}</td></tr>
<tr><td>Upload date</td><td>{{ bigfile.upload_date }}</td></tr>
<tr><td>Expire date</td><td>{{ bigfile.expire_date }}</td></tr>
<tr><td>Message</td><td>{{ bigfile.message }}</td></tr>
<tr><td>MD5</td><td>{{ bigfile.md5 }}</td></tr>

filebender/templates/bigfiles/upload.html
{% extends "base.html" %}

{% block content %}

  <h2>File Upload</h2>
  
  <script src="{{ MEDIA_URL }}js/sjcl.js" type="text/javascript"></script>
  <script src="{{ MEDIA_URL }}js/upload.js" type="text/javascript"></script>
  <script src="{{ MEDIA_URL }}js/BlobBuilder.js" type="text/javascript"></script>

  <form id="upload_javascript" enctype="multipart/form-data" method="post" action="/bigfiles/upload/">
     {% csrf_token %}

    <table>
        <tr>
            <td><label for="id_file">File:</label></td>
            <td><input type="file" name="file" id="id_file" onchange="upload.selected();"/></td>
        </tr>
        <tr>
            <td></td>
            <td>
                <div id="fileName"></div>
                <div id="fileSize"></div>
                <div id="fileType"></div>
                <div id="progressNumber"></div>         
            </td>
        </tr>
        <tr>
            <td><label for="id_message">Receiver:</label></td>
            <td>
                {{ form.receiver.errors }}
                {{ form.receiver }}
            </td>
        </tr>
        <tr>
            <td><label for="id_message">Message:</label></td>
            <td>
                {{ form.message.errors }}
                {{ form.message }}
            </td>
        </tr>
        <tr><td><label for="id_message">Expire Date:</label></td>
            <td>
                {{ form.expire_date.errors }}
                {{ form.expire_date }}
            </td>
        </tr>

          <tr>
            <td><label for="id_docrypt">Enable encryption:</label></td>
            <td><input type="checkbox" name="docrypt" id="id_docrypt" checked="true"></td>
        </tr>


        <tr>
            <td><label for="id_key">Key:</label></td>
            <td><input type="text" name="key" id="id_key" value="password"/></td>
        </tr>
        <tr><td></td><td>
            <input type="button" onclick="upload.start()" value="Upload" />
        </td></tr>
    </table>
    

  </form>

{% endblock %}